### ISSUE TITLE
The plugin relies on a non-existent class: GP_Translation_Memory How can I do it?

### ISSUE THREAD

**Issue by sunxiyuan** [Automattic/gp-translation-helpers#15]
This project seems to be just a user interface. Where do I need to find the implementation of the functions behind it? Thank you so much to anyone who can help ^_^

**Comment by dlind1** [comment]
Hello!
The implementation of GP_Translation_Memory is in a separate plugin, which has a lot of code specific to WordPress.com functionality (as well as another dependency on GP_Elasticsearch) and can't be really used on it's own without heavy modifications. If you'd like to see it anyway, we could publish that repository, but you'd have to re-implement a large portion of it to make it work.

**Comment by sunxiyuan** [comment]
I was really surprised to receive a reply, I originally thought it was a dead repository.
If you can release the code, it would be great. I would also like to study the implementation method of the memory.
I currently use the wporg-gp-translation-suggestions obtained from wordpress.org and the Pontoon project from Mozilla to implement a memory for GlotPress:
![image](https://user-images.githubusercontent.com/35832158/124754141-72be6e00-df5c-11eb-876d-ccdae8773742.png)

**Comment by sunxiyuan** [comment]
Oh, I just noticed that your reply contained "GP_Elasticsearch". 
I think I already know the implementation principle of memory, so I don't need to trouble you to publish this repository.
Thanks again for your reply!

**Comment by dlind1** [comment]
Sounds good, let me know if you'd need it after all or have some other questions 🙂
